Traceback (most recent call last):
  File "e:\bin\zapretgui\main.py", line 2, in <module>
    import debug_setup
  File "e:\bin\zapretgui\debug_setup.py", line 30, in <module>
    faulthandler.register(signal.SIGSEGV, file=open("zapret_faulthandler.log", "a"),
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'faulthandler' has no attribute 'register'
Traceback (most recent call last):
  File "e:\bin\zapretgui\main.py", line 2, in <module>
    import debug_setup
  File "e:\bin\zapretgui\debug_setup.py", line 29, in <module>
    faulthandler.register(signal.SIGSEGV, file=open("zapret_faulthandler.log", "a"),
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'faulthandler' has no attribute 'register'
Traceback (most recent call last):
  File "e:\bin\zapretgui\main.py", line 394, in initialize_managers_and_services
    from discord import DiscordManager
  File "e:\bin\zapretgui\discord.py", line 6, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "e:\bin\zapretgui\main.py", line 35, in <module>
    sys.stdout.reconfigure(encoding='utf-8')
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'reconfigure'
Traceback (most recent call last):
  File "e:\bin\zapretgui\main.py", line 34, in <module>
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'reconfigure'
Traceback (most recent call last):
  File "e:\bin\zapretgui\main.py", line 34, in <module>
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'reconfigure'
